pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            image 'python:2-alpine'
            args '-v /home/jack/jenkins-data:/var/jenkin_home'
        }
    }
    stages {
        stage('打包') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('单元测试') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('验收测试') {
            steps {
                sh 'python ./jenkins/scripts/seleniumDemp.py'
            }
        }
        stage('部署') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
